version: "3.1"
services:
  dbserver:
    image: mysql
    ports:
      - "3306:3306"
    hostname: dbserver
    container_name: dbserver
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: coffee_bear
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: PASSWORD
  server:
    image: flurdy/activator
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ~/.ivy2:/root/.ivy2
    tty: true
    container_name: server
    command: bash -c "cd /app && export PATH=$PATH:/opt/activator && activator run"
  client:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./front_app:/app
    tty: true
    container_name: client
    command: bash -c "cd /app && npm install && npm start"
